export type AlertSeverity = 'P0' | 'P1' | 'P2' | 'P3';

export const ALERT_SEVERITY_POLICY: Record<
  AlertSeverity,
  { label: string; page: boolean; examples: string[] }
> = {
  P0: {
    label: 'catastrophic service / security / financial integrity',
    page: true,
    examples: [
      'FINANCIAL_INVARIANT_VIOLATION',
      'SECURITY_AUTH_BYPASS_SUSPECTED',
      'DATA_CORRUPTION',
    ],
  },
  P1: {
    label: 'production service materially impaired',
    page: true,
    examples: [
      'DATABASE_UNAVAILABLE',
      'AUTH_SERVICE_UNAVAILABLE',
      'PAYMENT_CONFIRM_FAILURE_SPIKE',
      'READINESS_FAILURE',
      'MIGRATION_FAILED',
      'PAYMENT_REFUND_REQUIRED',
    ],
  },
  P2: {
    label: 'degraded behavior requiring investigation',
    page: false,
    examples: [
      'CALENDAR_SYNC_FAILURE_SPIKE',
      'ISOLATED_PAYMENT_FAILURE',
      'ELEVATED_LATENCY',
    ],
  },
  P3: {
    label: 'informational / hardening',
    page: false,
    examples: ['ISOLATED_4XX', 'DEPLOYMENT_STARTED'],
  },
};

/** Canonical event keys (observability + alerts). */
export const ObsEvents = {
  DEPLOYMENT_STARTED: 'DEPLOYMENT_STARTED',
  DEPLOYMENT_MIGRATION_STARTED: 'DEPLOYMENT_MIGRATION_STARTED',
  DEPLOYMENT_MIGRATION_SUCCEEDED: 'DEPLOYMENT_MIGRATION_SUCCEEDED',
  DEPLOYMENT_STARTED_APPLICATION: 'DEPLOYMENT_STARTED_APPLICATION',
  DEPLOYMENT_HEALTHCHECK_FAILED: 'DEPLOYMENT_HEALTHCHECK_FAILED',
  DEPLOYMENT_SMOKE_FAILED: 'DEPLOYMENT_SMOKE_FAILED',
  DEPLOYMENT_SUCCEEDED: 'DEPLOYMENT_SUCCEEDED',
  DEPLOYMENT_ROLLED_BACK: 'DEPLOYMENT_ROLLED_BACK',
  MIGRATION_STARTED: 'MIGRATION_STARTED',
  MIGRATION_SUCCEEDED: 'MIGRATION_SUCCEEDED',
  MIGRATION_FAILED: 'MIGRATION_FAILED',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  READINESS_FAILURE: 'READINESS_FAILURE',
  PAYMENT_REFUND_REQUIRED: 'PAYMENT_REFUND_REQUIRED',
  PAYMENT_CONFIRM_FAILURE: 'PAYMENT_CONFIRM_FAILURE',
  PAYMENT_INTENT_FAILURE: 'PAYMENT_INTENT_FAILURE',
  FINANCIAL_INVARIANT_VIOLATION: 'FINANCIAL_INVARIANT_VIOLATION',
  AUTH_OTP_PROVIDER_FAILURE: 'AUTH_OTP_PROVIDER_FAILURE',
  PROCESS_FATAL: 'PROCESS_FATAL',
  UNHANDLED_REJECTION: 'UNHANDLED_REJECTION',
  UNCAUGHT_EXCEPTION: 'UNCAUGHT_EXCEPTION',
  HTTP_5XX: 'HTTP_5XX',
} as const;

export type ObsEventKey = (typeof ObsEvents)[keyof typeof ObsEvents];
